# Generated by Django 5.0.2 on 2024-03-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orderitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
