# Generated by Django 5.0.2 on 2024-03-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_orderitem_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='created_at',
        ),
    ]
