# Generated by Django 5.0.2 on 2024-03-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_order_being_delivered_remove_order_coupon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
