# Generated by Django 5.0.2 on 2024-03-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_payment_stripe_charge_id_payment_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='address_type',
            field=models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
