# Generated by Django 5.0.2 on 2024-03-24 22:49

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_address_address_type_remove_address_zip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='08000000000', max_length=128, region=None),
        ),
    ]
