# Generated by Django 5.0.2 on 2024-03-24 22:51

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+2348123345432', max_length=128, region=None),
        ),
    ]
